#
# LECHO Config Makefile
#
# Copyright (c) 2000 The ThinLisp Group

CC=@CC@

ifdef OPT
CFLAGS=@CFLAGS@ -ansi -pedantic -W -Wall -fomit-frame-pointer -c
else
CFLAGS=@CFLAGS@ -ggdb3 -ansi -pedantic -W -Wall -c
endif

LINK=gcc -o

ifdef OPT
LINKFLAGS=-O2
LIBS= ../../tl/opt/libtl.a
else
LINKFLAGS=-g
LIBS= ../../tl/bin/libtl.a
endif

SYSLIBS=
OBJECTS= main.o boot.o echo.o

all : lecho.exe

clean :
	-rm *.o
	-( if [ -f lecho.exe ] ; then rm lecho.exe ; fi )

lecho.exe : makefile.config $(OBJECTS) $(LIBS)
	-( if [ -f lecho.exe ] ; then rm lecho.exe ; fi )
	$(LINK) lecho.exe $(LINKFLAGS) $(OBJECTS) $(LIBS) $(SYSLIBS)

%.o : ../c/%.c ../c/%.h makefile.config
	$(CC) $@ $(CFLAGS) -I ../c -I../../tl/c/ $<
