#
# LECHO Config Makefile
#
# Copyright (c) 1999 Jim Allard

CC=@CC@
CFLAGS=@CFLAGS@ -ggdb3 -ansi -pedantic -W -Wall -c
LINK=gcc -o
LINKFLAGS=-g
LIBS= ../../tl/bin/libtl.a
SYSLIBS=
OBJECTS= main.o boot.o echo.o

all : lecho.exe

clean :
	-rm *.o
	-( if [ -f lecho.exe ] ; then rm lecho.exe ; fi )

lecho.exe : makefile.config $(OBJECTS) $(LIBS)
	-( if [ -f lecho.exe ] ; then rm lecho.exe ; fi )
	$(LINK) lecho.exe $(LINKFLAGS) $(OBJECTS) $(LIBS) $(SYSLIBS)

%.o : ../c/%.c ../c/%.h makefile.config
	$(CC) $@ $(CFLAGS) -I ../c -I../../tl/c/ $<
